services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-api-festival-backend
    ports:
      - "8000:8000"
    env_file:
      - .env.backend
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rest-api-festival-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:3.6.23
    container_name: rest-api-festival-mongo
    ports:
      - "27017:27017"
    env_file:
      - .env.db
    volumes:
      - ./mongo_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: rest-api-festival-nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend
  #     - mongo

volumes:
  mongo_data:
